sudo: required
services:
    - docker

before_install:
    - docker build -t sokolovs/multi-container -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true sokolovs/multi-container npm test

after_success:
   - docker build -t sokolovs/multi-client ./client
   - docker build -t sokolovs/multi-nginx ./nginx
   - docker build -t sokolovs/multi-server ./server
   - docker build -t sokolovs/multi-worker ./worker
 
   - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

   - docker push sokolovs/multi-client
   - docker push sokolovs/multi-nginx
   - docker push sokolovs/multi-server
   - docker push sokolovs/multi-worker

